FROM --platform=$TARGETOS/$TARGETARCH openjdk:7u211-jre-alpine3.9

LABEL       author="XJHya" maintainer="2012036686@qq.com"

RUN apk add --no-cache --update curl ca-certificates openssl git tar bash sqlite fontconfig \
    && adduser --disabled-password --home /home/container container

USER container
ENV  USER=container HOME=/home/container

WORKDIR /home/container

COPY ./entrypoint.sh /entrypoint.sh

CMD ["/bin/bash", "/entrypoint.sh"]
